services:
  operations-db:
    image: bitnami/postgresql:latest
    container_name: operations-db
    ports:
      - "5483:5432"
    environment:
      - POSTGRES_USER=operations-dev
      - POSTGRES_PASSWORD=operations-dev
      - POSTGRES_DB=postgres
    volumes:
      - operations_db_data:/bitnami/postgresql

  broker:
    image: rabbitmq:3-management
    container_name: broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=broker-dev
      - RABBITMQ_DEFAULT_PASS=broker-dev
    volumes:
      - "rabbitmq_data:/var/lib/rambbitmq"

volumes:
  operations_db_data:
  rabbitmq_data:
